config/routes.rb
Rails.application.routes.draw do
  get 'notifications/index'
  get 'events/index'
  get 'events/new'
  get 'events/create'
  # get 'categories/index'
  # get 'categories/new'
  # get 'categories/create'
  # get 'category/index'
  # get 'category/new'
  # get 'category/create'
  # get 'event/index'
  # get 'event/new'
  # get 'event/create'
  # get 'bookings/index'
  # get 'bookings/new'
  # get 'bookings/create'
  # get 'roles/index'
  # get 'roles/new'
  # get 'roles/create'
  # get 'cities/index'
  # get 'cities/new'
  # get 'cities/create'
  # get 'users/index'
  # get 'users/new'
  # get 'users/create'
  # get 'locations/index'
  # get 'locations/new'

  # get 'locations/create'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  
  # get "/cities", to: "cities#new"
  resources :users do
    resources :bookings do
    put 'confirm'
    put 'cancel'
    end
  end

  resources :users, :locations, :cities, :roles, :categories, :events, :bookings, :notifications
  root "homes#index"
  
  get "/bookings/show", to: "bookings#show", as: "bookings_show"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
    belongs_to:user
    belongs_to:event
    enum status: { cancel: 0, confirm: 1, pending: 2 }
end

app/models/category.rb
class Category < ApplicationRecord
    has_many:events
    
end

app/models/city.rb
class City < ApplicationRecord
    has_many:location
end

app/models/event.rb
class Event < ApplicationRecord
    belongs_to:category
    has_many:users, through: :booking
    has_many:bookings
    belongs_to:location
    has_many:notifications, as: :notifiable

    after_create :create_notification

    private
    def create_notification
        self.notifications.create(message:"#{self.name} Event Update")
    end
end

app/models/location.rb
class Location < ApplicationRecord
    belongs_to:city
    has_many:events
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :notifiable, polymorphic: true
end

app/models/role.rb
class Role < ApplicationRecord
    has_and_belongs_to_many :users 
end

app/models/user.rb
class User < ApplicationRecord
    has_many:events, through: :booking
    has_many:bookings
    has_and_belongs_to_many :roles
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events=Event.all
  end

  def new
    @event=Event.new
  end

  def create
   
    @event = Event.new(event_params)
    if @event.save
      redirect_to events_index_path
    else
      render :new, status: :unprocessable_entity
    end
  end
  private

  def event_params
    params.require(:event).permit(:name, :start_time, :end_time, :category_id, :location_id)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
   
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  def index
    @roles=Role.all
  end

  def new
    @role=Role.new
  end

  def create
  
    @role=Role.new(role_params)
    if @role.save
      redirect_to roles_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  private
  
  def role_params
    params.require(:role).permit(:name)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
def index
    @users=User.all
end
def new
    @user=User.new
end
def create
  
    @user = User.new(user_params)
    @user.roles << Role.find_by(id: params[:user][:role_ids])
    if @user.save
      redirect_to users_path
    else
      render :new, status: :unprocessable_entity
    end
end
private

def user_params
  params.require(:user).permit(:name, :phone, :email, :role_id)
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/event_helper.rb
module EventHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/create.html.erb
<h1>Events#create</h1>
<p>Find me in app/views/events/create.html.erb</p>

app/views/events/index.html.erb
<h1>Events#index</h1>
<table>
<thead>
<tr>
<th>Name</th>
<th>Start Time</th>
<th>End Time</th>
<th>Location </th>
<th>Category</th>
<th>Left Seats</th>



</tr>
</thead>
<tbody>
<% @events.each do |e| %>
<tr>
    <td><%= e.name %></td>
    <td><%= e.start_time %></td>

    <td><%= e.end_time %></td>
    <td><%= e.location.name %></td>
    <td><%= e.category.name %></td>
    <td><%= e.location.capacity - e.bookings.sum(:capacity) %></td>
</tr>
<%end%>

</tbody>
</table>

<div>
<%= link_to "New Event", new_event_path %>
</div>


</body>
</html>

app/views/events/new.html.erb
<h1>Events#new</h1>
<%= form_with model: @event do |form| %>
    <p>
      <%= form.label :name %><br>
      <%= form.text_field :name %>
    </p>
    <p>
      <%= form.label :start_time %><br>
      <%= form.datetime_field :start_time %>
    </p>
    <p>
      <%= form.label :end_time %><br>
      <%= form.datetime_field :end_time %>
    </p>
    <p>
    <%= form.label :category %><br>
    <%=  collection_select( :event, :category_id , Category.all, :id, :name) %>
    </p>
    <p>
    <%= form.label :location %><br>
    <%=  collection_select( :event, :location_id , Location.all, :id, :name) %>
  
    </p>
    <p>
      <%= form.submit %>
    </p>
<% end %>